---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for internal DNS resolution

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:12-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "clojure"
            - name: POSTGRES_USER
              value: "clojure"
            - name: POSTGRES_DB
              value: "clojure"
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: clj-service
spec:
  type: NodePort
  selector:
    app: clj
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Optional, else K8s auto-selects a port in the 30000–32767 range

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clj
  template:
    metadata:
      labels:
        app: clj
    spec:
      containers:
        - name: clj
          image: dheeraj7444/webshop-app-clj:11
          env:
            - name: DB_HOST
              value: "db-service"
            - name: WEB_HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8080
          command: ["java", "-jar", "app.jar"]
